export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const LOAD_TOTAL_SUCCESS = 'LOAD_TOTAL_SUCCESS';     // price
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS';   // update DISH amount, TODO: deal with 0
export const REMOVE_DISH_SUCCESS = 'REMOVE_DISH_SUCCESS';   

//export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
//export const UPDATE_TOTAL_SUCCESS = 'UPDATE_TOTAL_SUCCESS';


